apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /tmp/train.py
            
            env:
            
            image: ravi-train
            workingDir: /tmp
          restartPolicy: OnFailure
