apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: %numWorkers%
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /tmp/train.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)            
            env:
            - name: modelDir
              value: $(modelDir)
            - name: exportDir
              value: $(exportDir)
            - name: trainSteps
              value: $(trainSteps)
            - name: batchSize
              value: $(batchSize)
            - name: learningRate
              value: $(learningRate)
            image: london-train
            name: tensorflow
            workingDir: /tmp
          restartPolicy: OnFailure
