apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: %numWorkers%
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /tmp/model.py
                     
            env:
            
            image: ravi-new-train
            name: tensorflow
            workingDir: /tmp
          restartPolicy: OnFailure
