apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Chief.yaml

namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.name
  name: trainingName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: ravi-train

